#ifndef H_TABIPB_CC_CUDA_H
#define H_TABIPB_CC_CUDA_H

#include <cstddef>
#include <cstdint>

extern "C" void cc_interact_cuda(
    int n,
    int n2,
    int n3,
    int num_interp_pts_per_node,
    int num_charges_per_node,
    double eps,
    double kappa,
    double kappa2,
    const double* clusters_x,
    const double* clusters_y,
    const double* clusters_z,
    const double* clusters_q,
    const double* clusters_q_dx,
    const double* clusters_q_dy,
    const double* clusters_q_dz,
    double* clusters_p,
    double* clusters_p_dx,
    double* clusters_p_dy,
    double* clusters_p_dz,
    const std::uint32_t* node_begin,
    const std::uint32_t* node_end,
    const std::uint32_t* cp_offsets,
    const std::uint32_t* cp_sources,
    const std::uint32_t* cc_offsets,
    const std::uint32_t* cc_sources,
    const double* elements_x,
    const double* elements_y,
    const double* elements_z,
    const double* sources_q,
    const double* sources_q_dx,
    const double* sources_q_dy,
    const double* sources_q_dz,
    std::size_t num_elements,
    std::size_t num_nodes,
    std::size_t cp_offsets_count,
    std::size_t cp_sources_count,
    std::size_t cc_offsets_count,
    std::size_t cc_sources_count,
    int enable_cp,
    void* stream);

extern "C" void cp_interact_cuda(
    int n,
    int n2,
    int n3,
    int num_interp_pts_per_node,
    int num_charges_per_node,
    double eps,
    double kappa,
    double kappa2,
    const double* clusters_x,
    const double* clusters_y,
    const double* clusters_z,
    double* clusters_p,
    double* clusters_p_dx,
    double* clusters_p_dy,
    double* clusters_p_dz,
    const std::uint32_t* node_begin,
    const std::uint32_t* node_end,
    const std::uint32_t* cp_offsets,
    const std::uint32_t* cp_sources,
    const double* elements_x,
    const double* elements_y,
    const double* elements_z,
    const double* sources_q,
    const double* sources_q_dx,
    const double* sources_q_dy,
    const double* sources_q_dz,
    std::size_t num_elements,
    std::size_t num_nodes,
    std::size_t cp_offsets_count,
    std::size_t cp_sources_count,
    void* stream);

#endif
