#include <iostream>
// #include <iomanip>
#include <cstdlib>
#include <cstring>

#include "boundary_element.h"
#include "elements.h"
#include "interaction_list.h"
#include "molecule.h"
#include "output.h"
#include "params.h"
#include "tabipb_timers.h"
#include "tree.h"

#ifdef USE_CUDA_CC
#include "cuda_helpers.h"
#endif

int main(int argc, char *argv[]) {
#ifdef USE_CUDA_CC
  // Initialize CUDA runtime/context before any module allocations.
  CUDA_CHECK(cudaSetDevice(0));
  CUDA_CHECK(cudaFree(nullptr));
#endif
  // set the parameter struct, which is read in from file provided as argv
  if (argc < 2) {
    std::cout << "No input file set. Exiting." << std::endl;
    std::exit(1);
  }
  struct Params params(argv[1]);
  struct Timers timers;
  const char* debug_env = std::getenv("TABIPB_DEBUG_PROGRESS");
  const char* require_all_env = std::getenv("TABIPB_CUDA_REQUIRE_ALL");
  const bool require_all = (require_all_env && std::strcmp(require_all_env, "0") != 0);
  const bool debug_progress = require_all ||
                              (debug_env && std::strcmp(debug_env, "0") != 0);

  timers.tabipb.start();

  // construct the biomolecule from the provided pqr file
  class Molecule molecule(params, timers.molecule);
  class Tree mol_tree(molecule, params.tree_max_per_leaf_, timers.tree);
  class InterpolationPoints mol_interp_pts(mol_tree, params.tree_degree_);

  if (params.input_mesh_prefix_.empty())
    molecule.build_xyzr_file();
  molecule.copyin_to_device();
  mol_interp_pts.copyin_to_device();
  mol_interp_pts.compute_all_interp_pts();

  // build particles from a NanoShaper surface generated by xyzr file
  // then build a tree on the particles, partitioning them
  class Elements elements(molecule, params, timers.elements);
  class Tree elem_tree(elements, params.tree_max_per_leaf_, timers.tree);
  class InterpolationPoints elem_interp_pts(elem_tree, params.tree_degree_);

  elements.copyin_to_device();
  elem_interp_pts.copyin_to_device();
  elem_interp_pts.compute_all_interp_pts();

  class InteractionList mol_ilist(mol_tree, params.tree_degree_,
                                  params.tree_theta_, timers.interaction_list);
  class InteractionList elem_ilist(elem_tree, params.tree_degree_,
                                   params.tree_theta_, timers.interaction_list);
  class InteractionList mol_elem_ilist(elem_tree, mol_tree, params.tree_degree_,
                                       params.tree_theta_,
                                       timers.interaction_list);

  // elements.compute_source_term();
  elements.compute_source_term(elem_interp_pts, elem_tree, molecule,
                               mol_interp_pts, mol_tree, mol_elem_ilist);

  /* energies, potential, and outfile routines are contained in output */
  class Output output(molecule, elements, params, timers.output);

  // initialize the boundary element method
  class BoundaryElement boundary_element(elements, elem_interp_pts, elem_tree,
                                         elem_ilist, molecule, params, output,
                                         timers.boundary_element);

  boundary_element.run_GMRES();

  if (debug_progress) {
    std::cerr << "[DEBUG] main: output.compute_coulombic_energy(FMM) begin\n";
  }
  output.compute_coulombic_energy(mol_interp_pts, mol_tree, mol_ilist);
  if (debug_progress) {
    std::cerr << "[DEBUG] main: output.compute_coulombic_energy(FMM) end\n";
    std::cerr << "[DEBUG] main: output.compute_solvation_energy(FMM) begin\n";
  }
  output.compute_solvation_energy(elem_interp_pts, elem_tree, mol_interp_pts,
                                  mol_tree, mol_elem_ilist);
  if (debug_progress) {
    std::cerr << "[DEBUG] main: output.compute_solvation_energy(FMM) end\n";
  }

  molecule.delete_from_device();
  mol_interp_pts.delete_from_device();

  elements.delete_from_device();
  elem_interp_pts.delete_from_device();

  output.finalize();

  timers.tabipb.stop();

  output.files(timers);

  return 0;
}
