#pragma once

#include <cstddef>

extern "C" {

void solvation_pp_cuda(
    const double* elem_x,
    const double* elem_y,
    const double* elem_z,
    const double* elem_q_dx,
    const double* elem_q_dy,
    const double* elem_q_dz,
    const double* elem_area,
    const double* mol_x,
    const double* mol_y,
    const double* mol_z,
    const double* mol_q,
    const double* potential,
    std::size_t potential_offset,
    std::size_t target_begin,
    std::size_t target_end,
    std::size_t source_begin,
    std::size_t source_end,
    double eps,
    double kappa,
    double* solv_eng,
    void* stream);

void solvation_pc_cuda(
    const double* elem_x,
    const double* elem_y,
    const double* elem_z,
    const double* elem_q_dx,
    const double* elem_q_dy,
    const double* elem_q_dz,
    const double* elem_area,
    const double* mol_clusters_x,
    const double* mol_clusters_y,
    const double* mol_clusters_z,
    const double* mol_clusters_q,
    const double* potential,
    std::size_t potential_offset,
    std::size_t source_node_idx,
    int num_mol_interp_pts_per_node,
    int num_mol_interp_charges_per_node,
    std::size_t target_begin,
    std::size_t target_end,
    double eps,
    double kappa,
    double* solv_eng,
    void* stream);

void solvation_cp_cuda(
    const double* mol_x,
    const double* mol_y,
    const double* mol_z,
    const double* mol_q,
    const double* elem_clusters_x,
    const double* elem_clusters_y,
    const double* elem_clusters_z,
    double* elem_clusters_p,
    double* elem_clusters_p_dx,
    double* elem_clusters_p_dy,
    double* elem_clusters_p_dz,
    std::size_t target_node_idx,
    int num_elem_interp_pts_per_node,
    int num_elem_interp_potentials_per_node,
    std::size_t source_begin,
    std::size_t source_end,
    double eps,
    double kappa,
    void* stream);

void solvation_cc_cuda(
    const double* mol_clusters_x,
    const double* mol_clusters_y,
    const double* mol_clusters_z,
    const double* mol_clusters_q,
    const double* elem_clusters_x,
    const double* elem_clusters_y,
    const double* elem_clusters_z,
    double* elem_clusters_p,
    double* elem_clusters_p_dx,
    double* elem_clusters_p_dy,
    double* elem_clusters_p_dz,
    std::size_t target_node_idx,
    std::size_t source_node_idx,
    int num_elem_interp_pts_per_node,
    int num_elem_interp_potentials_per_node,
    int num_mol_interp_pts_per_node,
    int num_mol_interp_charges_per_node,
    double eps,
    double kappa,
    void* stream);

void solvation_up_cuda(
    const double* mol_x,
    const double* mol_y,
    const double* mol_z,
    const double* mol_q,
    const double* mol_clusters_x,
    const double* mol_clusters_y,
    const double* mol_clusters_z,
    double* mol_clusters_q,
    const double* weights,
    int* exact_idx_x,
    int* exact_idx_y,
    int* exact_idx_z,
    double* denominator,
    std::size_t node_idx,
    int num_mol_interp_pts_per_node,
    int num_mol_interp_charges_per_node,
    std::size_t particle_start,
    std::size_t num_particles,
    void* stream);

void solvation_down_cuda(
    const double* elem_x,
    const double* elem_y,
    const double* elem_z,
    const double* elem_q_dx,
    const double* elem_q_dy,
    const double* elem_q_dz,
    const double* elem_area,
    const double* elem_clusters_x,
    const double* elem_clusters_y,
    const double* elem_clusters_z,
    const double* elem_clusters_p,
    const double* elem_clusters_p_dx,
    const double* elem_clusters_p_dy,
    const double* elem_clusters_p_dz,
    const double* potential,
    std::size_t potential_offset,
    const double* weights,
    std::size_t node_idx,
    int num_elem_interp_pts_per_node,
    int num_elem_interp_potentials_per_node,
    std::size_t particle_start,
    std::size_t num_particles,
    double* solv_eng,
    void* stream);

} // extern "C"
